[project]
name = "esp32-cambridge-transit-api"
description = "Aggregate API for Cambridge transit ESP32 project"
authors = [{ name = "awphi", email = "admin@adamw.ph" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.poetry]
packages = [{ include = "api", from = "src" }]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
